spring:
  application:
    name: demo-mq

  datasource: # mysql数据库连接
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testdemo?serverTimezone=GMT%2B8
    username: root
    password: 123456
server:
  port: 1000