spring:
  application:
    name: demo-mq

  datasource: # mysql数据库连接
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testdemo?serverTimezone=GMT%2B8
    username: root
    password: 123456

  rabbitmq:
    addresses: 192.168.72.10:5672
    connection-timeout: 5000
    username: guest
    password: guest
    virtual-host: /

server:
  port: 1000

mq:
  queue:
    name: "msg.fzh.demo"